apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app-container
        image: ajksaini2501/firstprogram:IMAGE_TAG
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
