name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: login to docker hub
      id: docker-hub
      env: 
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ajksaini2501/my-image-name:latest
    - name: List Docker images
      run: docker images
    - name: Push the Docker image
      run: docker push ajksaini2501/my-image-name:latest
      env:  
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  


    - name: authenticate to GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
    - name: setup cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }} 
    - name: Get GKE credentials
      run: gcloud container clusters get-credentials autopilot-cluster-1 --zone us-central1-a --project ${{ secrets.GCP_PROJECT_ID }}
    - name: Deploy to GKE
      run: |
        kubectl apply -f deployment.yml
        kubectl apply -f service.yml
  
