name: Docker Image CI

on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: login to docker hub
      id: docker-hub
      env: 
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ajksaini2501/my-image-name:latest
    - name: List Docker images
      run: docker images
    - name: Push the Docker image
      run: docker push ajksaini2501/my-image-name:latest
      env:  
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  
    - name: authenticate to GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
    - name: setup cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'
        project_id: ${{ secrets.GCP_PROJECT_ID }}       
    - name: Get GKE credentials
      uses: google-github-actions/get-gke-credentials@v2
      with:
        cluster_name: cluster-1
        location: us-central1-a
        project_id: ${{ secrets.GCP_PROJECT_ID }}
      env:
        CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE: /home/runner/work/DevOps/DevOps/gha-creds.json
        GOOGLE_APPLICATION_CREDENTIALS: /home/runner/work/DevOps/DevOps/gha-creds.json
        GOOGLE_GHA_CREDS_PATH: /home/runner/work/DevOps/DevOps/gha-creds.json
        CLOUDSDK_CORE_PROJECT: unified-gift-466615-b4
        CLOUDSDK_PROJECT: unified-gift-466615-b4
        GCLOUD_PROJECT: unified-gift-466615-b4
        GCP_PROJECT: unified-gift-466615-b4
        GOOGLE_CLOUD_PROJECT: unified-gift-466615-b4

    - name: Deploy to GKE
      run: |
        kubectl apply -f deployment.yml
        kubectl apply -f service.yml

